### ISSUE TITLE
Spellcheck is not working

### ISSUE THREAD

**Issue by Makkori** [careteditor/caret#260]
Both "Check spelling" and "Autocorrect spelling" seem to have no effect in v2.0.0. Was working fine in v1.15.1. Running Linux Ubuntu 16.04.

**Comment by astoilkov** [comment]
Spellchecking should now work on Linux in Caret 2.0.1. Thanks for reporting.

Closing this issue.

**Comment by huwd** [comment]
@Makkori Can you confirm this now works for you? I'm still not getting any luck on Linux see below:
OS: Ubuntu 17.04
```bash
$ Locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE=en_GB.UTF-8
```
![no_spellcheck](https://cloud.githubusercontent.com/assets/3694062/26688534/cc248880-46ea-11e7-9669-948c2c68f62c.png)

**Comment by huwd** [comment]
@astoilkov is your understanding this is remains resolved? I'm wondering if this is something to do with not having the dictionaries set up - but then I'm reading you do spellcheck from within the app? Any idea how I could resolve a situation like the one above?

**Comment by astoilkov** [comment]
Hi @huwd,

Sorry for the delay. Under Linux Caret includes an English dictionary as part of the application. There is nothing that depends on the Linux distribution so the spellchecking should work. We have two Linux test machines and both have a working spellchecking for the latest version of Caret.

I would recommend opening a new issue because this issue was already resolved and it doesn't seem to be the same problem. What you can try is install [Atom](https://atom.io) and check if the spellchecking works there. Did you have a time when the spellchecking worked for you? In what version?

**Comment by GeneralBison** [comment]
I also have this problem with Caret. 
As far as I know it has never worked for me, I'm using Version 2.1.3 on Ubuntu 17.04.

![image](https://user-images.githubusercontent.com/2755919/26926382-714c9596-4c45-11e7-948a-de08d10da77b.png)

**Comment by huwd** [comment]
sorry @astoilkov I've been remiss in following this up have opened a new issue [#449](https://github.com/careteditor/caret/issues/449).

**Comment by huwd** [comment]
@GeneralBison I notice you are also running ubuntu 17.04, can you confirm if you also had this problem on <=16.10?

I can't remember if this is something new or not over on [#449](https://github.com/careteditor/caret/issues/449).

**Comment by GeneralBison** [comment]
@huwd I recall also having this problem on 16.10, not 100% certain though.
