### ISSUE TITLE
Typing is broken in v2.0.11

### ISSUE THREAD

**Issue by onury** [careteditor/caret#306]
Cannot use Caret (version 2.0.11)  any more :(

- Cursor jumps when editing a word in the middle of a line.
- Select a word and make italic (add surrounding _) is impossible.
- ..

**Comment by astoilkov** [comment]
Hi @onury,

We are trying to reproduce the issue but without success. Can you help us with a little more information. Does this happen every time? Can you send us the text with which happens and the steps to reproduce?

Thanks in advance.

**Comment by onury** [comment]
Hi, yes this happens every time. I think the cursor position is off when you select or position it on.

Pls see the animated GIF attached.

![caret-issue-306](https://cloud.githubusercontent.com/assets/3665990/25187352/6bbbda2e-252b-11e7-8a32-93814759c07f.gif)

**Comment by astoilkov** [comment]
I see you have inline code inside of the italic. Does the issue happen on lines that only have italic in them?

Thanks a lot for the information.

**Comment by onury** [comment]
Code block is affecting yes.. but as in the video, I'm not exactly dealing inside the code block, but rather before the block. Also It seems if I start the selection from within a code, cursor position is off.

**Comment by astoilkov** [comment]
Thanks for all the information. We will start working on this. Expect a fix soon.

**Comment by pslobo** [comment]
I can also reproduce this. Doesn't happen with bold, only italic and it doesn't seem to be related to the type of font used since I've tested with a couple (monospace and non-monospace)

**Comment by astoilkov** [comment]
The issue is now fixed. Expect a release soon.

**Comment by pslobo** [comment]
Confirmed fixed on my end.

**Comment by onury** [comment]
Still not fixed. See below, especially within tables:

<img width="672" alt="cursor" src="https://cloud.githubusercontent.com/assets/3665990/25961768/1ccb697e-3684-11e7-91bd-04ae104805f3.png">

Captured this without manually changing the cursor position. The position here in the last line is the natural position when you finish typing the sentence.

**Comment by pslobo** [comment]
Yeah, confirmed within tables. Other than that, I haven't been able to reproduce the initially reported error. Even typing the above text outside a table works just fine, tables boggle it up.

**Comment by onury** [comment]
<img width="207" alt="1" src="https://cloud.githubusercontent.com/assets/3665990/25962572/f10fefa0-3686-11e7-93d8-4cb5adb6b875.png">

<img width="190" alt="2" src="https://cloud.githubusercontent.com/assets/3665990/25962577/f479e2ea-3686-11e7-89ad-50fbe794463f.png">

<img width="432" alt="3" src="https://cloud.githubusercontent.com/assets/3665990/25962587/f8f05872-3686-11e7-9f01-eba2dda533cf.png">

Again, the cursor position here is the natural position when you finish typing.

**Comment by astoilkov** [comment]
Thanks for all the reports. Some issues were different from others but we think we fixed all of them in Caret 2.1.2 release.

Closing this issue. Feel free to post here if you find any familiar issues.

Thanks for reporting.

**Comment by onury** [comment]
v2.1.2 still has problems

![table](https://cloud.githubusercontent.com/assets/3665990/26009510/d235d998-3751-11e7-912a-503a05aed6b5.gif)

![select](https://cloud.githubusercontent.com/assets/3665990/26009628/5aa82664-3752-11e7-8233-c3025d375ebf.gif)

![bold](https://cloud.githubusercontent.com/assets/3665990/26009637/5f5d8bb8-3752-11e7-9e35-74311f500632.gif)

**Comment by astoilkov** [comment]
@onury - Sorry for the inconvenience. We now also fixed this scenario internally. The fix will be included in the next 2.1.3 release. Thanks!

**Comment by onury** [comment]
@astoilkov no problem at all. You're doing a great job. 
cheers

**Comment by astoilkov** [comment]
@onury  - 2.1.3 release now includes the fix

**Comment by onury** [comment]
@astoilkov thanks for the update. working nicely.
