### ISSUE TITLE
Last whitespace character in a link displayed as `%20` in preview when certain characters used in previous links

### ISSUE THREAD

**Issue by dealingwith** [careteditor/caret#367]
I use Caret to edit Jekyll posts, which allow for `{{site.baseurl}}` variables, which I use inside internal links in case I ever move the blog:

<img width="1228" alt="screen shot 2017-05-13 at 9 52 55 am" src="https://cloud.githubusercontent.com/assets/124208/26026509/1818a1a0-37c2-11e7-882c-95bf21d39afd.png">

Prior to the most recent update, these links did not preview correctly (they would not be formatted into links, I would see all the raw markdown). I just updated and now they display (they do not link anywhere, which is expected--Caret could have no idea how to handle that variable), which is great!

Now there is just one more odd bug..._external_ links following the above nicely formatted link text end up with `%20` for spaces in only the _last_ contiguous whitespace character(s) of their text:

<img width="1236" alt="screen shot 2017-05-13 at 9 44 55 am" src="https://cloud.githubusercontent.com/assets/124208/26026548/e9ed1de6-37c2-11e7-95c2-fa7bd2a4642c.png">

<img width="1247" alt="screen shot 2017-05-13 at 9 56 45 am" src="https://cloud.githubusercontent.com/assets/124208/26026549/ef4c921c-37c2-11e7-82aa-d4b7f02f02dd.png">

<img width="1232" alt="screen shot 2017-05-13 at 9 59 34 am" src="https://cloud.githubusercontent.com/assets/124208/26026550/f51e2034-37c2-11e7-9e04-44fe9322cd79.png">

**Comment by dealingwith** [comment]
Note that this _only_ happens if there are links with the `{{site.baseurl}}` variable in the document. All links in documents without them are fine.

**Comment by dealingwith** [comment]
Also note that is only links that occur after the variable that are affected. 

<img width="943" alt="screen shot 2017-05-13 at 10 04 50 am" src="https://cloud.githubusercontent.com/assets/124208/26026593/b90b71a4-37c3-11e7-9bfa-07100d14da78.png">

**Comment by dealingwith** [comment]
_Also_ note that other links _with_ the variable are not affected! 😄

**Comment by dealingwith** [comment]
These `%20` whitespace characters also show up in the PDF export.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 2.1.3 release.

Closing this issue. Thank you for reporting.

**Comment by joshuaiz** [comment]
I'm using the 4.0.0beta9 and this issue is still there:

<img width="1358" alt="screen shot 2018-03-12 at 10 21 04 pm" src="https://user-images.githubusercontent.com/1096738/37323913-bc005f2c-2643-11e8-9105-1416891016bf.png">

**Comment by joshuaiz** [comment]
Just to follow up, deleting the links and then undoing all the deletions seems to fix this but then it brings up the 'Cannot find module 'emojis' - 4.0.0-beta9 #669' issue so I think these are related. 

I'd be happy to have a setting to disable emojis entirely until these bugs are worked out.

**Comment by astoilkov** [comment]
The emojis error will be fixed in the next release. We will also take a look at the link issue.
