### ISSUE TITLE
Another exception :(

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#511]
The following error has occurred:
```
{
    "message": "Cannot set property 'text' of undefined",
    "version": "3.4.4",
    "os": "Windows 10",
    "path": "C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Path\\PathWrap.js",
    "code": "(r-=2),t.splice(r,2),t[r].text=\"...\"}},",
    "line": 5,
    "column": 1476,
    "stack": [
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1476)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1317)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:888)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:704)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\extensions\\Title.js:5:1724)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resources\\app.asar\\web\\Events.js:5:1335)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.4\\resour

**Comment by astoilkov** [comment]
Does it happen again for file `Dropbox > Apps > DanClarkeBlog > 2017-08-PassionForDev - post.md` or for another path?

**Comment by dracan** [comment]
A different subdirectory, similar path though.

**Comment by dracan** [comment]
Note that the "-" in your path should be a backslash. The file was called post.md.

**Comment by astoilkov** [comment]
@dracan Can you try updating to 3.4.5?

**Comment by dracan** [comment]
@astoilkov I'll give it a try at lunchtime, I'm not on my laptop at the mo. Thanks for the very quick update though! :-)

**Comment by dracan** [comment]
@astoilkov Sorry, only just had chance to try it. It doesn't crash in the latest version, however it's also not rendering the path at the top. It just says `post.md`. And if I make any changes at all - even the `post.md` then disappears and is replaced with the `*`.

**Comment by astoilkov** [comment]
Do you have enough space for more than the file name to be visible? What happens if you have the window full size and the preview closed?

**Comment by dracan** [comment]
Closing the preview window does show the path, and the filename doesn't disappear this time when I the *modified* apostrophe is present. So that all seem as expected.

This all has worked fine in the past though - so surely something in a recent-ish update introduced this and #493? When I first started using Caret, I did see a full path, and I didn't experience any exceptions.

Either way though - I'm not that bothered about the path not being present. The filename disappearing when in the `*` is present feels like a bug however.

**Comment by astoilkov** [comment]
Yes. We will fix the `*` problem.

We introduced path shortening because the file name is now on the most right side of the title which means that when there isn't enough space the filename won't be visible which is the most important part of the path. The issue [here](https://github.com/careteditor/caret/issues/194) describes the problem in a better way.

However, from what you are describing I started wondering if the shortener misfunctions in your case. I attached a GIF so you could check out the way the wrapping should work. Does this happen on your machine?

![title](http://g.recordit.co/3bAZU7ntkl.gif)

**Comment by dracan** [comment]
Seems to be doing weird flickering things as I resize! Hard to explain, so here's an animated gif ...

![caret](https://user-images.githubusercontent.com/567988/29634747-bbc55c5a-8842-11e7-8fc3-3b8b14c61f08.gif)

Could this be doing this each alternating pixel as I resize because of the 200x scaling?

**Comment by astoilkov** [comment]
I am not entirely sure why it is doing this. We will investigate. Thanks a lot for the gif. This explains a lot.

**Comment by astoilkov** [comment]
The issues with path wrapping should be fixed now. Can you update Caret and check if everything works on your side?

**Comment by dracan** [comment]
It's *better*, but still not right. In my animated gif above where it's flicking between text and no-text as I resize - it's now flicking between having a path and filename VS filename only without path. Seem to alternate as I resize in a similar way to the above screenshot.

This doesn't really matter though, as is only noticeable if you're resizing. But still seems a bit strange.

**Comment by astoilkov** [comment]
The last standing issue with the title has been resolved in the new Caret 4.0 Beta available [here](https://caret.io/4beta/).

Closing this issue.

I would love to hear your feedback on the new beta release. Have a great day.
