### ISSUE TITLE
Preview is broken

### ISSUE THREAD

**Issue by bearhagen** [careteditor/caret#535]
When I click CTRL+SHIFT+R my preview is broken. It doesn't hide the markup, and it only covers a small portion of the left side of the window.

https://gfycat.com/UnripeScientificAcornbarnacle

Also, nothing happens when I change preview theme: https://gfycat.com/PinkImmaterialBoilweevil

This is a fresh install of 3.4.6 on Windows 10

**Comment by astoilkov** [comment]
Hi @bearhagen,

I have tried to replicate the issue by freshly installing Caret 3.4.6 on Windows 10. I wasn't able to reproduce the problem. Is it possible that you try uninstalling Caret, removing the `C:/Users/your-user/AppData/Roaming/Caret` folder and installing Caret again?

**Comment by bearhagen** [comment]
I've already uninstalled twice. Removed everything in AppData as well.
I also tried installing 3.4.4 and updating, but still the same issue. I have multiple computers running 3.4.6 that don't have the issue.

**Comment by astoilkov** [comment]
I think I have a theory why it may not be working. Can you check the permissions of the `C:/Users/your-user/AppData/Roaming/Caret/Themes` folder? The issue could be replicated if the files are not there or if the app doesn't have permission to access them.

**Comment by bearhagen** [comment]
I tried giving `Everyone` and `Users` full read and write access, but doesn't seem to have any effect.

I don't know if it's related or not, but if I go to the Windows Event Viewer, Caret keeps giving this error:

```
Faulting application name: Caret.exe, version: 3.4.6.0, time stamp: 0x595426ff
Faulting module name: ntdll.dll, version: 10.0.15063.608, time stamp: 0x802f667e
Exception code: 0xc0000005
Fault offset: 0x000408e4
Faulting process id: 0x3a04
Faulting application start time: 0x01d330bc4d41b063
Faulting application path: C:\Users\Bjørnar\AppData\Local\Caret\app-3.4.6\Caret.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 0fcfab53-8b0a-4468-af39-5522f5c48071
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by astoilkov** [comment]
This seems to be an Electron issue described [here](https://github.com/electron/electron/issues/10188). We will update Electron to fix this error. I will write here again after we release a new version so we could test if this will fix the preview problem.

**Comment by astoilkov** [comment]
Hi @bearhagen,

We have a new Caret 4.0 update available [here](https://caret.io/4beta/) which should resolve the issue. You could test it to see if everything works there.

Closing this issue.

**Comment by bjornarhagen** [comment]
Great! Love the updates 👍
Unfortunately preview is still broken for me. Weird that it happens on my desktop and not on my laptop. 
I no longer get the error in the windows event viewer though.

![https://i.xdh.no/2c7625f50695](https://i.xdh.no/2c7625f50695)

**Comment by astoilkov** [comment]
Does the same thing happen for Split/Live Preview?

**Comment by bjornarhagen** [comment]
Nope. Split/Live preview works fine, except I can't change the preview theme.

**Comment by Zifiv** [comment]
I've the same issue on Windows 1 Home for Caret 3.4.6 and Caret Beta 4.0.0-rc5.
Preview themes is not working.

It's strange because I've installer Caret on a Windows Seven it work correctly.

**Comment by astoilkov** [comment]
@beaucoralk Can you share a screenshot of the problem? Thanks in advance.

**Comment by bjornarhagen** [comment]
I just updated to 4.0.0-rc5. The issue is still here for me.
Short video of it: https://i.xdh.no/151b2f41f402

As you can see the live preview works fine (except not being able to change theme), and full preview is broken.

Last time I posted this bug was only on my desktop, while my laptop had no issues with Caret. Since then I have done a fresh install of Windows, and now the issue is on my laptop as well.

**Comment by astoilkov** [comment]
@bearhagen Did you change the version of Windows you have installed on your laptop? What version have you installed on the laptop?

**Comment by bjornarhagen** [comment]
@astoilkov nope. I have windows 10 pro (v1709 build 16299.309) on both my computers. Didn't change it on the laptop, only did a fresh install.
