### ISSUE TITLE
scrollbar in dark mode isn't dark

### ISSUE THREAD

**Issue by Amparose** [careteditor/caret#588]
Only tested on OSX so far but the scrollbar when in Dark Mode is the same as light mode and clashes enough to be quite distracting.

**Comment by erusev** [comment]
I agree. We've addressed the issue in 4.0. Beta's coming on 3rd of January.

**Comment by astoilkov** [comment]
This is now fixed in the latest [Caret 4.0 Beta release](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.

**Comment by Amparose** [comment]
In beta2 this is not fixed.

<img width="743" alt="screenshot 2018-01-07 12 07 47" src="https://user-images.githubusercontent.com/949192/34648876-7add9532-f3a3-11e7-9228-cbc836f26e4b.png">

**Comment by erusev** [comment]
We thought you meant the scrollbar in the sidebar.

About the editor scrollbar, does the scrollbar always have this white background?

Does it ever appear without the white background, like this:

![image](https://user-images.githubusercontent.com/184170/34649055-aed66bfa-f3af-11e7-8b9a-c82f2961286c.png)


This is how it looks on my Mac.

**Comment by Amparose** [comment]
Oh right, sorry I should have posted a screenshot initially. So far I have not been able to get it to look like your image from fiddling with opening and closing, resizing the window, or redownloading the beta.

The white scrollbar background is even present on windows that have no overflow:

![screenshot 2018-01-10 12 01 43](https://user-images.githubusercontent.com/949192/34769467-2eef8ace-f5fe-11e7-87df-f3887a90be3c.png)

Anything I ought to try?

**Comment by astoilkov** [comment]
Hi @Amparose,

The issue is caused by `Show scroll bars` option inside `System Preferences -> General`. If you select `Show scroll bars: When scrolling` the white should disappear.

![image](https://user-images.githubusercontent.com/884810/34816726-67359192-f6be-11e7-83c4-f6c4abc4ea1c.png)

Additionally, we will look into this issue and research how we can resolve it. Thanks for all the information.

**Comment by Amparose** [comment]
Just a note that that preference may indeed be a solution for some but I already had it set to that and had the issue. Beta 8 doesn't seem to have the white scrollbar for me though so hopefully that is the bug squashed.
