### ISSUE TITLE
Nested task list

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#711]
In 4.0.0-rc4, put cursor at the end of this and press Enter:

```md
- [ ] Hello
    - [ ] Nested
        - [ ] List
        - [ ] item
```

I get this:

```md
- [ ] Hello
    - [ ] Nested
        - [ ] List
        - [ ] item
        - [     
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks Borek!

**Comment by borekb** [comment]
Thanks for the update, it's behaving better now but I still encounter issues in _some_ lists, for example, this one:

![image](https://user-images.githubusercontent.com/101152/38238522-5e606bc6-372a-11e8-8ab2-7b425f25da10.png)

Note the slightly different "g" and "i" items, it also previews incorrectly:

![image](https://user-images.githubusercontent.com/101152/38238547-74df072c-372a-11e8-8864-e163046eec6e.png)

**UPDATE:** it's because there are multiple spaces inside some brackets! When I copy/paste the source here, it becomes:

```txt
- [ ] a
    - [ ] b
    - [ ] c
    - [ ] d:
        - [ ] e
        - [ ] f
        - [   ] g
        - [ ] h
        - [   ] i
    - [ ] j
```

This makes the problem quite obvious. I'm not sure how multiple spaces ended up there, I don't manually edit check boxes, is it possible that Caret somehow put more spaces there when continuing lists?

**Comment by astoilkov** [comment]
I have tried to write the same list as you in Caret but wasn't able to replicate the problem. Keep an eye on it and if you find what is causing it you could create a new issue. Thanks!

**Comment by borekb** [comment]
Will do. I have a _feeling_ that in v4, sometimes, my Markdown documents contain several spaces in a row, for example, three are suddenly three spaces after the final dot in a paragraph. But I don't have enough hard data on it, it's also possible that I mistakenly write the spaces somehow so I'll be watching this and report back if I spot something repeatable.
