### ISSUE TITLE
Spell Check: How to Turn On?

### ISSUE THREAD

**Issue by dlumma** [careteditor/caret#802]
Hi There!

I have never been able to see spell check work in the multiple versions of Caret Beta I've used. Is there a special trick to "turning this feature on"?

Thanks!
-Denali

**Comment by stegsaurus** [comment]
I was just about to open an issue for a similar problem. It seems that in the last few versions of Caret on Windows, spell checking is not working properly.

You can toggle this option at **Edit > Check Spelling | Autocorrect spelling**. This works for a while, but it seems that after I've been working in Caret for a bit, spellcheck simply stops working. I can enter blatant typos like "wnpwdn" and it doesn't underline them. This has introduced more typos into my articles, which is frustrating.

Spellcheck works when I close and re-open Caret, but having it stop in the middle of writing an article is really unreliable.

I'm using Caret 4.0.0-rc18 on Windows 10 Pro, version 1803.

**Comment by astoilkov** [comment]
We have released a new version of Caret which has some fixes for problems we successfully replicated. Can you update and let us know if your issue is also resolved?

Thanks in advance.

**Comment by daniel-varela** [comment]
Hi, I'm running the 4.0 RC 20 (on macOS) and I still can't get spell checking. Not even after restarting Caret. Is there a way to open the debugger?

**Comment by astoilkov** [comment]
@daniel-varela Can you check if `Edit -> Check Spelling` is checked? What language do you write in?

**Comment by daniel-varela** [comment]
It is checked. I also tried enabling auto correct spelling, which doesn't work as well.

I was writing in german when I noticed it, but even if I restart Caret, create a new file and start writing in english, it won't correct my errors.

Also for background information: My macOS system language is set to english. In the _Language and Preferences_ settings my preferred languages are set to german and english, while english is set as primary language.
